package com.beardness.macosmsapp.ui.theme.color

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF00668A)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFC3E7FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001E2C)
val md_theme_light_secondary = Color(0xFF4E616D)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD1E5F4)
val md_theme_light_onSecondaryContainer = Color(0xFF0A1E28)
val md_theme_light_secondaryFixed = Color(0xFFD1E5F4)
val md_theme_light_onSecondaryFixed = Color(0xFF0A1E28)
val md_theme_light_secondaryFixedDim = Color(0xFFB5C9D7)
val md_theme_light_onSecondaryFixedVariant = Color(0xFF364955)
val md_theme_light_tertiary = Color(0xFF605A7D)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFE6DEFF)
val md_theme_light_onTertiaryContainer = Color(0xFF1C1736)
val md_theme_light_tertiaryFixed = Color(0xFFE6DEFF)
val md_theme_light_onTertiaryFixed = Color(0xFF1C1736)
val md_theme_light_tertiaryFixedDim = Color(0xFFCAC1EA)
val md_theme_light_onTertiaryFixedVariant = Color(0xFF484264)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFBFCFF)
val md_theme_light_onBackground = Color(0xFF191C1E)
val md_theme_light_outline = Color(0xFF71787D)
val md_theme_light_inverseOnSurface = Color(0xFFF0F1F3)
val md_theme_light_inverseSurface = Color(0xFF2E3133)
val md_theme_light_inversePrimary = Color(0xFF7AD0FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF00668A)
val md_theme_light_outlineVariant = Color(0xFFC0C7CD)
val md_theme_light_scrim = Color(0xFF000000)
val md_theme_light_surface = Color(0xFFF8F9FC)
val md_theme_light_onSurface = Color(0xFF191C1E)
val md_theme_light_surfaceVariant = Color(0xFFDCE3E9)
val md_theme_light_onSurfaceVariant = Color(0xFF41484D)
val md_theme_light_surfaceContainerHighest = Color(0xFFE1E2E5)
val md_theme_light_surfaceContainerHigh = Color(0xFFE7E8EA)
val md_theme_light_surfaceContainer = Color(0xFFEDEEF0)
val md_theme_light_surfaceContainerLow = Color(0xFFF3F3F6)
val md_theme_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_theme_light_surfaceDim = Color(0xFFD9DADC)
val md_theme_light_surfaceBright = Color(0xFFF8F9FC)

val md_theme_dark_primary = Color(0xFF7AD0FF)
val md_theme_dark_onPrimary = Color(0xFF003549)
val md_theme_dark_primaryContainer = Color(0xFF004C69)
val md_theme_dark_onPrimaryContainer = Color(0xFFC3E7FF)
val md_theme_dark_primaryFixed = Color(0xFFC3E7FF)
val md_theme_dark_onPrimaryFixed = Color(0xFF001E2C)
val md_theme_dark_primaryFixedDim = Color(0xFF7AD0FF)
val md_theme_dark_onPrimaryFixedVariant = Color(0xFF004C69)
val md_theme_dark_secondary = Color(0xFFB5C9D7)
val md_theme_dark_onSecondary = Color(0xFF20333E)
val md_theme_dark_secondaryContainer = Color(0xFF364955)
val md_theme_dark_onSecondaryContainer = Color(0xFFD1E5F4)
val md_theme_dark_secondaryFixed = Color(0xFFD1E5F4)
val md_theme_dark_onSecondaryFixed = Color(0xFF0A1E28)
val md_theme_dark_secondaryFixedDim = Color(0xFFB5C9D7)
val md_theme_dark_onSecondaryFixedVariant = Color(0xFF364955)
val md_theme_dark_tertiary = Color(0xFFCAC1EA)
val md_theme_dark_onTertiary = Color(0xFF322C4C)
val md_theme_dark_tertiaryContainer = Color(0xFF484264)
val md_theme_dark_onTertiaryContainer = Color(0xFFE6DEFF)
val md_theme_dark_tertiaryFixed = Color(0xFFE6DEFF)
val md_theme_dark_onTertiaryFixed = Color(0xFF1C1736)
val md_theme_dark_tertiaryFixedDim = Color(0xFFCAC1EA)
val md_theme_dark_onTertiaryFixedVariant = Color(0xFF484264)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C1E)
val md_theme_dark_onBackground = Color(0xFFE1E2E5)
val md_theme_dark_outline = Color(0xFF8A9297)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1E)
val md_theme_dark_inverseSurface = Color(0xFFE1E2E5)
val md_theme_dark_inversePrimary = Color(0xFF00668A)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF7AD0FF)
val md_theme_dark_outlineVariant = Color(0xFF41484D)
val md_theme_dark_scrim = Color(0xFF000000)
val md_theme_dark_surface = Color(0xFF111416)
val md_theme_dark_onSurface = Color(0xFFC5C6C9)
val md_theme_dark_surfaceVariant = Color(0xFF41484D)
val md_theme_dark_onSurfaceVariant = Color(0xFFC0C7CD)
val md_theme_dark_surfaceContainerHighest = Color(0xFF333537)
val md_theme_dark_surfaceContainerHigh = Color(0xFF282A2C)
val md_theme_dark_surfaceContainer = Color(0xFF1D2022)
val md_theme_dark_surfaceContainerLow = Color(0xFF191C1E)
val md_theme_dark_surfaceContainerLowest = Color(0xFF0C0F10)
val md_theme_dark_surfaceDim = Color(0xFF111416)
val md_theme_dark_surfaceBright = Color(0xFF37393C)


val LightThemeColors = lightColorScheme(
    primary = md_theme_light_primary,
    onPrimary = md_theme_light_onPrimary,
    primaryContainer = md_theme_light_primaryContainer,
    onPrimaryContainer = md_theme_light_onPrimaryContainer,
    secondary = md_theme_light_secondary,
    onSecondary = md_theme_light_onSecondary,
    secondaryContainer = md_theme_light_secondaryContainer,
    onSecondaryContainer = md_theme_light_onSecondaryContainer,
    tertiary = md_theme_light_tertiary,
    onTertiary = md_theme_light_onTertiary,
    tertiaryContainer = md_theme_light_tertiaryContainer,
    onTertiaryContainer = md_theme_light_onTertiaryContainer,
    error = md_theme_light_error,
    errorContainer = md_theme_light_errorContainer,
    onError = md_theme_light_onError,
    onErrorContainer = md_theme_light_onErrorContainer,
    background = md_theme_light_background,
    onBackground = md_theme_light_onBackground,
    outline = md_theme_light_outline,
    inverseOnSurface = md_theme_light_inverseOnSurface,
    inverseSurface = md_theme_light_inverseSurface,
    inversePrimary = md_theme_light_inversePrimary,
    surfaceTint = md_theme_light_surfaceTint,
    outlineVariant = md_theme_light_outlineVariant,
    scrim = md_theme_light_scrim,
    surface = md_theme_light_surface,
    onSurface = md_theme_light_onSurface,
    surfaceVariant = md_theme_light_surfaceVariant,
    onSurfaceVariant = md_theme_light_onSurfaceVariant,
)

val DarkThemeColors = darkColorScheme(
    primary = md_theme_dark_primary,
    onPrimary = md_theme_dark_onPrimary,
    primaryContainer = md_theme_dark_primaryContainer,
    onPrimaryContainer = md_theme_dark_onPrimaryContainer,
    secondary = md_theme_dark_secondary,
    onSecondary = md_theme_dark_onSecondary,
    secondaryContainer = md_theme_dark_secondaryContainer,
    onSecondaryContainer = md_theme_dark_onSecondaryContainer,
    tertiary = md_theme_dark_tertiary,
    onTertiary = md_theme_dark_onTertiary,
    tertiaryContainer = md_theme_dark_tertiaryContainer,
    onTertiaryContainer = md_theme_dark_onTertiaryContainer,
    error = md_theme_dark_error,
    errorContainer = md_theme_dark_errorContainer,
    onError = md_theme_dark_onError,
    onErrorContainer = md_theme_dark_onErrorContainer,
    background = md_theme_dark_background,
    onBackground = md_theme_dark_onBackground,
    outline = md_theme_dark_outline,
    inverseOnSurface = md_theme_dark_inverseOnSurface,
    inverseSurface = md_theme_dark_inverseSurface,
    inversePrimary = md_theme_dark_inversePrimary,
    surfaceTint = md_theme_dark_surfaceTint,
    outlineVariant = md_theme_dark_outlineVariant,
    scrim = md_theme_dark_scrim,
    surface = md_theme_dark_surface,
    onSurface = md_theme_dark_onSurface,
    surfaceVariant = md_theme_dark_surfaceVariant,
    onSurfaceVariant = md_theme_dark_onSurfaceVariant,
)